on:
  push:
    branches:
      - master
jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew :desktop:packageDmg

      - name: Upload build binaries
        uses: actions/upload-artifact@v2
        with:
          name: build-binaries-macos
          path: '**/build/compose/binaries'